// <auto-generated>
/*
 * OpenAPI Petstore
 *
 * This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenAPIClientUtils = Org.OpenAPITools.Client.ClientUtils;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// BillingInvoiceCustomer
    /// </summary>
    public partial class BillingInvoiceCustomer : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BillingInvoiceCustomer" /> class.
        /// </summary>
        /// <param name="customerId"></param>
        /// <param name="customerId">customerId</param>
        /// <param name="name">name</param>
        [JsonConstructor]
        public BillingInvoiceCustomer(CustomerId? customerId, string customerId, string name)
        {
            CustomerId = customerId;
            CustomerId = customerId;
            Name = name;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="BillingInvoiceCustomer" /> class.
        /// </summary>
        /// <param name="customerDetails"></param>
        /// <param name="customerId">customerId</param>
        /// <param name="name">name</param>
        [JsonConstructor]
        public BillingInvoiceCustomer(CustomerDetails? customerDetails, string customerId, string name)
        {
            CustomerDetails = customerDetails;
            CustomerId = customerId;
            Name = name;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets CustomerId
        /// </summary>
        public CustomerId? CustomerId { get; set; }

        /// <summary>
        /// Gets or Sets CustomerDetails
        /// </summary>
        public CustomerDetails? CustomerDetails { get; set; }

        /// <summary>
        /// Gets or Sets CustomerId
        /// </summary>
        [JsonPropertyName("customerId")]
        public string CustomerId { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BillingInvoiceCustomer {\n");
            sb.Append("  CustomerId: ").Append(CustomerId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="BillingInvoiceCustomer" />
    /// </summary>
    public class BillingInvoiceCustomerJsonConverter : JsonConverter<BillingInvoiceCustomer>
    {
        /// <summary>
        /// Deserializes json to <see cref="BillingInvoiceCustomer" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override BillingInvoiceCustomer Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            string? customerId = default;
            string? name = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? propertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (propertyName)
                    {
                        case "customerId":
                            customerId = utf8JsonReader.GetString();
                            break;
                        case "name":
                            name = utf8JsonReader.GetString();
                            break;
                        default:
                            break;
                    }
                }
            }

            if (customerId == null)
                throw new ArgumentNullException(nameof(customerId), "Property is required for class BillingInvoiceCustomer.");

            if (name == null)
                throw new ArgumentNullException(nameof(name), "Property is required for class BillingInvoiceCustomer.");

            Utf8JsonReader customerIdReader = utf8JsonReader;
            if (Client.ClientUtils.TryDeserialize<CustomerId>(ref customerIdReader, jsonSerializerOptions, out CustomerId? customerId))
                return new BillingInvoiceCustomer(customerId, customerId, name);

            Utf8JsonReader customerDetailsReader = utf8JsonReader;
            if (Client.ClientUtils.TryDeserialize<CustomerDetails>(ref customerDetailsReader, jsonSerializerOptions, out CustomerDetails? customerDetails))
                return new BillingInvoiceCustomer(customerDetails, customerId, name);

            throw new JsonException();
        }

        /// <summary>
        /// Serializes a <see cref="BillingInvoiceCustomer" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="billingInvoiceCustomer"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, BillingInvoiceCustomer billingInvoiceCustomer, JsonSerializerOptions jsonSerializerOptions)
        {
            System.Text.Json.JsonSerializer.Serialize(writer, billingInvoiceCustomer.CustomerId, jsonSerializerOptions);

            System.Text.Json.JsonSerializer.Serialize(writer, billingInvoiceCustomer.CustomerDetails, jsonSerializerOptions);

            writer.WriteStartObject();

            writer.WriteString("customerId", billingInvoiceCustomer.CustomerId);
            writer.WriteString("name", billingInvoiceCustomer.Name);

            writer.WriteEndObject();
        }
    }
}
