// <auto-generated>
/*
 * OpenAPI Petstore
 *
 * This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenAPIClientUtils = Org.OpenAPITools.Client.ClientUtils;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// BillingInvoice
    /// </summary>
    public partial class BillingInvoice : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BillingInvoice" /> class.
        /// </summary>
        /// <param name="billingId">billingId</param>
        /// <param name="customer">customer</param>
        [JsonConstructor]
        public BillingInvoice(string billingId, BillingInvoiceCustomer customer)
        {
            BillingId = billingId;
            Customer = customer;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets BillingId
        /// </summary>
        [JsonPropertyName("billingId")]
        public string BillingId { get; set; }

        /// <summary>
        /// Gets or Sets Customer
        /// </summary>
        [JsonPropertyName("customer")]
        public BillingInvoiceCustomer Customer { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BillingInvoice {\n");
            sb.Append("  BillingId: ").Append(BillingId).Append("\n");
            sb.Append("  Customer: ").Append(Customer).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="BillingInvoice" />
    /// </summary>
    public class BillingInvoiceJsonConverter : JsonConverter<BillingInvoice>
    {
        /// <summary>
        /// Deserializes json to <see cref="BillingInvoice" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override BillingInvoice Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            string? billingId = default;
            BillingInvoiceCustomer? customer = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? propertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (propertyName)
                    {
                        case "billingId":
                            billingId = utf8JsonReader.GetString();
                            break;
                        case "customer":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                customer = JsonSerializer.Deserialize<BillingInvoiceCustomer>(ref utf8JsonReader, jsonSerializerOptions);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (billingId == null)
                throw new ArgumentNullException(nameof(billingId), "Property is required for class BillingInvoice.");

            if (customer == null)
                throw new ArgumentNullException(nameof(customer), "Property is required for class BillingInvoice.");

            return new BillingInvoice(billingId, customer);
        }

        /// <summary>
        /// Serializes a <see cref="BillingInvoice" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="billingInvoice"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, BillingInvoice billingInvoice, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            writer.WriteString("billingId", billingInvoice.BillingId);
            writer.WritePropertyName("customer");
            JsonSerializer.Serialize(writer, billingInvoice.Customer, jsonSerializerOptions);

            writer.WriteEndObject();
        }
    }
}
